mysite/mainApp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('landing/', views.landing, name='landing'),
    path('debug/', views.DebugTest, name='DebugTest')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls'))
]

mysite/orders/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
]

mysite/products/urls.py
from django.urls import path, include
from . import views

urlpatterns = [

]

mysite/mainApp/models.py
from django.db import models

# Create your models here.
class Subscriber(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField()

    def __str__(self):
        return "%s | %s" % (self.email, self.name)
    
    class Meta:
        verbose_name = "Subscriber"
        verbose_name_plural = "Subscribers"

mysite/orders/models.py
from django.db import models
from products.models import Product
from django.db.models.signals import post_save

class Status(models.Model):
    name = models.CharField(max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % (self.name)
    
    class Meta:
        verbose_name = "Status order"
        verbose_name_plural = "Status orders"


# Create your models here.
class Order(models.Model):
    customer_name =  models.CharField(max_length=64, blank=True, null=True, default=None)
    customer_email = models.EmailField(blank=True, null=True, default=None)
    customer_phone = models.CharField(max_length=48, blank=True, null=True, default=None)
    customer_address = models.CharField(max_length=128, blank=True, null=True, default=None)
    comments = models.TextField(blank=True, null=True, default=None)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)    #total price for all products in order
    status = models.ForeignKey(Status, blank=True, null=True, default=None, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "Order: %s %s" % (self.id, self.status.name)
    
    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"

    def save(self, *args, **kwargs):
        super(Order, self).save(*args, **kwargs)


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.PROTECT)
    number = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)    # price*number
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % (self.product.name)

    class Meta:
        verbose_name = "Product In Order"
        verbose_name_plural = "Products In Order"

    def save(self, *args, **kwargs):
        # current price
        self.price_per_item = self.product.price
        # total per item
        self.total_price = self.number * self.price_per_item

        super(ProductInOrder, self).save(*args, **kwargs)


def product_in_order_post_save(sender, instance, create=False, **kwargs):
    # all price
    order = instance.order
    all_product_in_order = ProductInOrder.objects.filter(order=order, is_active=True)

    order_total_price = 0
    for item in all_product_in_order:
        order_total_price += item.total_price

    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)


post_save.connect(product_in_order_post_save, sender=ProductInOrder,)

mysite/products/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name =  models.CharField(max_length=128, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % (self.name)
    
    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.PROTECT)
    image = models.ImageField(upload_to="product_images/")
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % (self.id)
    
    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"

mysite/mainApp/forms.py
from django import forms
from .models import *

class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        #fields = ['name','email']
        exclude = ['']

mysite/mainApp/views.py
from django.shortcuts import render
from .forms import SubscriberForm
from products.models import Product

# Create your views here.
def home(request):
    products = Product.objects.filter(is_active=True)
    return render(request, 'mainApp/home.html', locals())


def landing(request):
    print(request.method)
    if request.method == 'POST':
        form = SubscriberForm(request.POST)         
        if(form.is_valid()):   
            form = form.save()
            #refresh
    else:
        form = SubscriberForm(None)    
    return render(request, 'mainApp/landing.html', locals())

def DebugTest(request):
    if request.method == 'POST':
        form = SubscriberForm(request.POST)
        if form.is_valid():
            pass  # does nothing, just trigger the validation
    else:
        form = SubscriberForm()
    return render(request, 'mainApp/debug.html', {'form': form})

mysite/orders/views.py
from django.shortcuts import render

# Create your views here.

mysite/products/views.py
from django.shortcuts import render

# Create your views here.

mysite/mainApp/templates/mainApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Shop 1 </title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'mainApp/mainStyle.css'%}" type="text/css">

</head>
<body>
{% include 'mainApp/navbar.html' %}

{% block content %}
{% endblock content %}

{% include 'mainApp/footer.html' %}

 <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>

</body>
</html>

mysite/mainApp/templates/mainApp/debug.html
{% extends 'mainApp/wrapper.html' %}

{% block content %}
<div class="container top-container">
    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <h1>Comming soon</h1>
        <h1>Leave your email</h1>
        <form class="form" method='post' action=''>
            {% csrf_token %}
            <div class="form-group">
                <label for="id_email">Your email: </label>
                <input type="email" class="form-control" name="email" value="" maxlength="254" required="" id="id_email">
            </div>
            <div class="form-group">
                <label for="id_name">Your name: </label>
                <input type="text" class="form-control" name="name" value="" maxlength="128" required="" id="id_name">
            </div>
            <input type='submit' value='Submit' id='submit' name='submit'>
        </form>
    </div>
    </div>
</div>
{% endblock  %}

mysite/mainApp/templates/mainApp/footer.html
 <footer class="footer">
      <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
      </div>
 </footer>

mysite/mainApp/templates/mainApp/home.html
{% extends 'mainApp/base.html' %}


{% load static %}

{% block content %}
    <div class="section-top">
        <img src="{% static 'mainApp/image/mainPic.png' %}" class="img-responsive">
    </div>
    <div class="section">
        <div class="container">
            <div class="row">

                {% for product in products %}
                    <div class="col-lg-3">
                        <div class="product-item">
                            <div>
                                <img src="/" class="img-responsive">
                            </div>
                            <h5>{{ product.name }}</h5>
                            <p>
                                {{ product.description | truncatechars_html:100 }}
                            </p>
                            <div class="add-to-card-btn">
                                <button class="btn btn-success">
                                    Buy
                                </button>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

mysite/mainApp/templates/mainApp/includes/some_html.html
{% block content %}
<p>Встроеный блок include 1</p>
<p>Встроеный блок include 2</p>
<p>Встроеный блок include 3</p>
{% endblock  %}

mysite/mainApp/templates/mainApp/landing.html
{% extends 'mainApp/wrapper.html' %}

 <link rel="stylesheet" href="{% static 'mainApp/landing.css'%}" type="text/css">


{% block content %}
<div>
<div class="container">
    <div class="row top-row">
    <div class="col-lg-8 col-lg-offset-4">
        <h1>Comming soon</h1>
        <h1>Leave your email</h1>
        <form class="form" method='post' action=''>
            {% csrf_token %}
            <div class="form-group">
                <label for="id_email">Your email: </label>
                <!--{{form.email}}-->
                <input type="email" name="{{form.email.name}}" class="form-control"
            </div>
            <div class="form-group">
                <label for="id_name">Your name: </label>
                <input type="text" name="{{form.name.name}}" class="form-control"
            </div>
            <button type='submit' class="btn btn-primary" value='' id='submit' name='submit'>Submit</button>
        </form>
    </div>
    </div>
</div>
</div>  
{% endblock  %}

mysite/mainApp/templates/mainApp/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

mysite/mainApp/templates/mainApp/wrapper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Shop 1 </title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'mainApp/mainStyle.css'%}" type="text/css">
    
</head>
<body>
  <div class="jumbotron top-container">
      {% block content %}
      {% endblock %}
  </div>
</body>
</html>